// <auto-generated />
namespace Touche.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class text_to_message_in_reviews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(text_to_message_in_reviews));
        
        string IMigrationMetadata.Id
        {
            get { return "201707180827342_text_to_message_in_reviews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
